<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Base.Core.RequestResponse" Version="9.0.3" />
    <PackageReference Include="Base.Extensions.Translations.Abstractions" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Trading.Core.Resources\Trading.Core.Resources.csproj" />
  </ItemGroup>
</Project>